import base64
import io
import json
import math
import os
import random
import struct
import textwrap
import time
import wave
from datetime import datetime

import gspread
import pandas as pd
import streamlit as st
import streamlit.components.v1 as components
from google.oauth2.service_account import Credentials
from openai import OpenAI


# -------------------------------
# Page Config and Global UI Theme
# -------------------------------
st.set_page_config(
    page_title="AI Retrospective Assistant",
    layout="wide",
    page_icon="🚀",
)

st.title("AI Retrospective Assistant")
st.caption("Smarter retrospectives | Better decisions | Faster delivery")

FILE_NAME = "sprint_data.csv"
GOOGLE_SHEET_NAME = "Retro Data"
GOOGLE_SHEETS_SCOPE = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]
SPRINT_WORKSHEET_NAME = "Sprint Insights"
CONFIG_WORKSHEET_NAME = "Config"
RESPONSES_WORKSHEET_NAME = "Responses"
ACTION_WORKSHEET_NAME = "Actions"
ACTION_SHEET_COLUMNS = ["Action", "Priority", "Source"]
TEAM_ACTION_SOURCE = "Team Added"
AI_ACTION_SOURCE = "Generated by AI"
MOOD_WORKSHEET_NAME = "Mood Tracker"
MOOD_SHEET_COLUMNS = ["Team Name", "PI or Sprint Name", "Average Mood Score", "Status of Team"]
DEFAULT_SPIN_QUESTIONS = [
    "🚀 What went well?",
    "😕 What didn't go well?",
    "⛔ Biggest blocker?",
    "💡 Improvement idea?",
    "🔥 What frustrated you?",
    "🎯 One experiment for next sprint?",
    "🤝 Team collaboration feedback?",
]

RETRO_QUESTION_MAP = {
    "5 Whys": [
        "Why did stories spill over?",
        "Why was estimation inaccurate?",
        "Why were dependencies missed?",
    ],
    "Fishbone": [
        "What are the root causes of defects?",
        "Are tools or process causing quality issues?",
        "Where is quality breaking most often?",
    ],
    "Sprint Detective": [
        "Where did work get stuck this sprint?",
        "Which stories caused spillover and why?",
        "What recurring flow patterns do we see?",
    ],
    "Metrics Retro": [
        "Why is velocity fluctuating sprint to sprint?",
        "Are we overcommitting compared to capacity?",
        "Is capacity planned with enough buffer?",
    ],
    "Mad-Sad-Glad": [
        "What made you happy this sprint?",
        "What frustrated you most this sprint?",
        "What can improve team morale next sprint?",
    ],
}


def get_streamlit_secrets() -> dict:
    """Safely return Streamlit secrets mapping, even when secrets.toml is absent."""
    try:
        return dict(st.secrets)
    except Exception:
        return {}


def get_openai_api_key() -> tuple[str | None, str, list[str]]:
    """Resolve OpenAI API key across local env and multiple Streamlit secrets layouts."""
    secrets = get_streamlit_secrets()
    candidates: list[tuple[str | None, str]] = [
        (os.getenv("OPENAI_API_KEY"), "env:OPENAI_API_KEY"),
    ]

    secret_keys: list[str] = []
    try:
        secret_keys = list(secrets.keys())
    except Exception:
        secret_keys = []

    if "OPENAI_API_KEY" in secrets:
        candidates.append((secrets.get("OPENAI_API_KEY"), "secrets:OPENAI_API_KEY"))
    if "openai_api_key" in secrets:
        candidates.append((secrets.get("openai_api_key"), "secrets:openai_api_key"))
    if "api_key" in secrets:
        candidates.append((secrets.get("api_key"), "secrets:api_key"))

    if "openai" in secrets:
        openai_section = secrets["openai"]
        if hasattr(openai_section, "get"):
            candidates.extend(
                [
                    (openai_section.get("api_key"), "secrets:openai.api_key"),
                    (openai_section.get("OPENAI_API_KEY"), "secrets:openai.OPENAI_API_KEY"),
                ]
            )

    # Last resort: scan nested secrets recursively for key-like fields.
    def scan_mapping(mapping, prefix: str = "secrets"):
        discovered: list[tuple[str | None, str]] = []
        if not hasattr(mapping, "items"):
            return discovered
        for key, value in mapping.items():
            key_str = str(key)
            lower_key = key_str.lower()
            path = f"{prefix}.{key_str}"
            if lower_key in {"openai_api_key", "api_key"}:
                discovered.append((value, path))
            if hasattr(value, "items"):
                discovered.extend(scan_mapping(value, path))
        return discovered

    candidates.extend(scan_mapping(secrets))

    for value, source in candidates:
        if value and str(value).strip():
            return str(value).strip(), source, secret_keys

    return None, "not-found", secret_keys


@st.cache_data(show_spinner=False)
def generate_spin_sound() -> bytes:
    """Synthesise a short spinning-wheel whoosh as WAV bytes (stdlib only)."""
    sample_rate = 44100
    duration = 1.5
    num_samples = int(sample_rate * duration)
    buf = io.BytesIO()
    with wave.open(buf, "w") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(sample_rate)
        frames = []
        for i in range(num_samples):
            t = i / sample_rate
            progress = t / duration
            # frequency sweeps 800 Hz → 200 Hz (wheel slowing down)
            freq = 800 * (1 - progress) + 200 * progress
            # amplitude envelope peaks in the middle
            amplitude = 32767 * math.sin(math.pi * progress) * 0.7
            sample = int(amplitude * math.sin(2 * math.pi * freq * t))
            frames.append(struct.pack("<h", max(-32768, min(32767, sample))))
        wav.writeframes(b"".join(frames))
    return buf.getvalue()


@st.cache_data(show_spinner=False)
def generate_timer_end_sound() -> bytes:
    """Create a short beep used when a question timer completes."""
    sample_rate = 44100
    duration = 0.8
    frequency = 880
    num_samples = int(sample_rate * duration)
    buf = io.BytesIO()
    with wave.open(buf, "w") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(sample_rate)
        frames = []
        for i in range(num_samples):
            t = i / sample_rate
            fade_multiplier = min(1.0, t * 10) * min(1.0, (duration - t) * 10)
            amplitude = 32767 * 0.35 * fade_multiplier
            sample = int(amplitude * math.sin(2 * math.pi * frequency * t))
            frames.append(struct.pack("<h", max(-32768, min(32767, sample))))
        wav.writeframes(b"".join(frames))
    return buf.getvalue()


def get_credentials_file_path() -> str:
    base_dir = os.path.dirname(os.path.abspath(__file__))
    candidate_paths = [
        os.path.join(base_dir, "credentials.json"),
        os.path.join(base_dir, "..", "credentials.json"),
        os.path.join(base_dir, "..", "..", "credentials.json"),
        os.path.join(base_dir, "..", "..", "..", "credentials.json"),
    ]

    for candidate_path in candidate_paths:
        resolved_path = os.path.abspath(candidate_path)
        if os.path.exists(resolved_path):
            return resolved_path

    raise FileNotFoundError(
        "credentials.json was not found. Add it near the app or configure st.secrets['gcp_service_account']."
    )


@st.cache_resource(show_spinner=False)
def get_google_workbook():
    secrets = get_streamlit_secrets()

    if "gcp_service_account" in secrets:
        credentials = Credentials.from_service_account_info(
            dict(secrets["gcp_service_account"]),
            scopes=GOOGLE_SHEETS_SCOPE,
        )
    else:
        credentials = Credentials.from_service_account_file(
            get_credentials_file_path(),
            scopes=GOOGLE_SHEETS_SCOPE,
        )

    client = gspread.authorize(credentials)
    return client.open(GOOGLE_SHEET_NAME)


@st.cache_resource(show_spinner=False)
def get_or_create_worksheet(title: str, rows: int = 100, cols: int = 20):
    workbook = get_google_workbook()
    try:
        return workbook.worksheet(title)
    except gspread.WorksheetNotFound:
        return workbook.add_worksheet(title=title, rows=rows, cols=cols)


@st.cache_data(show_spinner=False, ttl=30)
def get_sheet_records(title: str, rows: int = 100, cols: int = 20) -> list[dict]:
    sheet = get_or_create_worksheet(title, rows=rows, cols=cols)
    return sheet.get_all_records()


@st.cache_data(show_spinner=False, ttl=30)
def get_sheet_row_values(title: str, row_number: int, rows: int = 100, cols: int = 20) -> list[str]:
    sheet = get_or_create_worksheet(title, rows=rows, cols=cols)
    return sheet.row_values(row_number)


@st.cache_data(show_spinner=False, ttl=30)
def get_sheet_cell_value(title: str, cell_ref: str, rows: int = 100, cols: int = 20) -> str:
    sheet = get_or_create_worksheet(title, rows=rows, cols=cols)
    return sheet.acell(cell_ref).value or ""


def clear_google_sheet_read_cache() -> None:
    for cached_reader in [get_sheet_records, get_sheet_row_values, get_sheet_cell_value]:
        clear_method = getattr(cached_reader, "clear", None)
        if callable(clear_method):
            clear_method()


def set_flash_message(scope: str, level: str, message: str) -> None:
    st.session_state[f"flash_{scope}"] = {"level": level, "message": message}


def show_flash_message(scope: str) -> None:
    flash_message = st.session_state.pop(f"flash_{scope}", None)
    if not flash_message:
        return

    level = str(flash_message.get("level", "info"))
    message = str(flash_message.get("message", ""))
    if level == "success":
        st.success(message)
    elif level == "warning":
        st.warning(message)
    elif level == "error":
        st.error(message)
    else:
        st.info(message)


def apply_pending_session_resets() -> None:
    pending_keys = st.session_state.pop("_pending_session_resets", [])
    for key in pending_keys:
        if key in st.session_state:
            value = st.session_state[key]
            if isinstance(value, str):
                st.session_state[key] = ""
            elif isinstance(value, int):
                st.session_state[key] = 0
            elif isinstance(value, float):
                st.session_state[key] = 0.0
            elif isinstance(value, list):
                st.session_state[key] = []


def clear_session_keys(*keys: str) -> None:
    pending_keys = st.session_state.setdefault("_pending_session_resets", [])
    for key in keys:
        if key not in pending_keys:
            pending_keys.append(key)


def get_mood_status(score: float) -> str:
    if score < 2.5:
        return "Team is struggling"
    if score < 4:
        return "Team is okay but needs improvement"
    return "Team is performing great"


def save_mood_data_to_google_sheet(team_name: str, sprint_name: str, average_mood: float, mood_status: str) -> None:
    sheet = get_or_create_worksheet(MOOD_WORKSHEET_NAME, rows=500, cols=10)
    existing_header = get_sheet_row_values(MOOD_WORKSHEET_NAME, 1, rows=500, cols=10)

    if existing_header != MOOD_SHEET_COLUMNS:
        sheet.clear()
        sheet.append_row(MOOD_SHEET_COLUMNS)

    sheet.append_row([
        team_name,
        sprint_name,
        f"{average_mood:.2f}",
        mood_status,
    ])
    clear_google_sheet_read_cache()


def save_sprint_data_to_google_sheet(df: pd.DataFrame, columns: list[str]) -> None:
    sheet = get_or_create_worksheet(SPRINT_WORKSHEET_NAME, rows=200, cols=len(columns) + 5)
    rows = df.reindex(columns=columns).fillna("").values.tolist()

    sheet.clear()
    sheet.append_row(columns)
    if rows:
        sheet.append_rows(rows)
    clear_google_sheet_read_cache()


def ensure_action_sheet_schema(sheet) -> None:
    existing_header = [header.strip() for header in sheet.row_values(1)]

    if not existing_header:
        sheet.append_row(ACTION_SHEET_COLUMNS)
        return

    for column_index, header in enumerate(ACTION_SHEET_COLUMNS, start=1):
        if len(existing_header) < column_index or existing_header[column_index - 1] != header:
            sheet.update_cell(1, column_index, header)


def normalize_action_dataframe(action_df: pd.DataFrame) -> pd.DataFrame:
    normalized_df = action_df.copy()

    if normalized_df.empty:
        return pd.DataFrame(columns=ACTION_SHEET_COLUMNS)

    if "Action" not in normalized_df.columns:
        if "Action Item" in normalized_df.columns:
            normalized_df["Action"] = normalized_df["Action Item"]
        elif "Task" in normalized_df.columns:
            normalized_df["Action"] = normalized_df["Task"]
        else:
            normalized_df["Action"] = ""

    if "Priority" not in normalized_df.columns:
        if "Status" in normalized_df.columns:
            status_series = normalized_df["Status"].astype(str).str.strip().str.lower()
            normalized_df["Priority"] = status_series.map(
                {
                    "open": "Medium",
                    "in progress": "High",
                    "done": "Low",
                    "high": "High",
                    "medium": "Medium",
                    "low": "Low",
                }
            ).fillna("Medium")
        else:
            normalized_df["Priority"] = "Medium"

    if "Source" not in normalized_df.columns:
        normalized_df["Source"] = TEAM_ACTION_SOURCE

    normalized_df["Action"] = normalized_df["Action"].astype(str).str.strip()
    normalized_df["Priority"] = normalized_df["Priority"].astype(str).str.strip().str.title()
    normalized_df["Source"] = normalized_df["Source"].astype(str).str.strip()
    normalized_df.loc[normalized_df["Source"] == "", "Source"] = TEAM_ACTION_SOURCE
    normalized_df.loc[
        ~normalized_df["Source"].isin([TEAM_ACTION_SOURCE, AI_ACTION_SOURCE]),
        "Source",
    ] = TEAM_ACTION_SOURCE
    normalized_df = normalized_df[normalized_df["Action"] != ""].copy()
    normalized_df.loc[~normalized_df["Priority"].isin(["High", "Medium", "Low"]), "Priority"] = "Medium"
    return normalized_df[ACTION_SHEET_COLUMNS]


def render_question_timer(question: str, duration_seconds: int, timer_reset_key: str) -> None:
    if duration_seconds <= 0:
        return

    beep_base64 = base64.b64encode(generate_timer_end_sound()).decode()
    storage_seed = f"{question}|{duration_seconds}|{timer_reset_key}"

    components.html(
        f"""
        <div style=\"padding: 0.75rem 1rem; border-radius: 0.75rem; background: #fff7ed; border: 1px solid #fdba74; color: #9a3412; font-family: sans-serif;\">
            <div style=\"font-size: 0.85rem; margin-bottom: 0.2rem;\">Question timer</div>
            <div id=\"retro-timer-display\" style=\"font-size: 1.8rem; font-weight: 700; letter-spacing: 0.04em;\">--:--</div>
            <div id=\"retro-timer-status\" style=\"font-size: 0.85rem; margin-top: 0.2rem;\">Beep will play when time finishes.</div>
        </div>
        <script>
        const durationSeconds = {duration_seconds};
        const seed = {json.dumps(storage_seed)};
        const timerKey = `retro-question-timer-${{seed}}`;
        const timerDoneKey = `retro-question-timer-done-${{seed}}`;
        const display = document.getElementById('retro-timer-display');
        const status = document.getElementById('retro-timer-status');
        const endSound = new Audio('data:audio/wav;base64,{beep_base64}');
        let endTime = Number(window.localStorage.getItem(timerKey) || 0);

        if (!endTime || Number.isNaN(endTime) || endTime <= Date.now()) {{
            endTime = Date.now() + durationSeconds * 1000;
            window.localStorage.setItem(timerKey, String(endTime));
            window.localStorage.removeItem(timerDoneKey);
        }}

        function formatRemaining(totalSeconds) {{
            const safeSeconds = Math.max(0, totalSeconds);
            const minutes = String(Math.floor(safeSeconds / 60)).padStart(2, '0');
            const seconds = String(safeSeconds % 60).padStart(2, '0');
            return `${{minutes}}:${{seconds}}`;
        }}

        function tick() {{
            const remainingMs = endTime - Date.now();
            const remainingSeconds = Math.ceil(remainingMs / 1000);

            if (remainingMs <= 0) {{
                display.textContent = '00:00';
                status.textContent = 'Time is up.';
                if (!window.localStorage.getItem(timerDoneKey)) {{
                    window.localStorage.setItem(timerDoneKey, '1');
                    endSound.play().catch(() => {{}});
                }}
                return;
            }}

            display.textContent = formatRemaining(remainingSeconds);
            status.textContent = remainingSeconds <= 10 ? 'Finishing soon...' : 'Beep will play when time finishes.';
        }}

        tick();
        window.setInterval(tick, 250);
        </script>
        """,
        height=110,
    )


def ensure_spill_over_column(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    if all(col in df.columns for col in ["Committed", "Scope Added", "Completed"]):
        df["Spill Over"] = (
            pd.to_numeric(df["Committed"], errors="coerce").fillna(0)
            + pd.to_numeric(df["Scope Added"], errors="coerce").fillna(0)
            - pd.to_numeric(df["Completed"], errors="coerce").fillna(0)
        )
    return df


def mark_sync_event(label: str) -> None:
    st.session_state["last_sync_time"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    st.session_state["last_sync_event"] = label


RETRO_CATEGORY_WEIGHTS = {
    "Delivery": 0.30,
    "Quality": 0.25,
    "Inventory": 0.20,
    "Productivity": 0.15,
    "People": 0.10,
}

RETRO_PRIORITY_ORDER = ["Delivery", "Quality", "Inventory", "Productivity", "People"]

RETRO_CATEGORY_MAP = {
    "Delivery": "5 Whys",
    "Quality": "Fishbone",
    "Inventory": "Sprint Detective",
    "Productivity": "Metrics Retro",
    "People": "Mad-Sad-Glad",
}

RETRO_REASON_MAP = {
    "Delivery": "Low predictability or commitment mismatch.",
    "Quality": "Increase in defects is impacting quality.",
    "Inventory": "High spillover indicates flow and WIP issues.",
    "Productivity": "Velocity instability is affecting throughput.",
    "People": "Team morale is limiting delivery effectiveness.",
}


def normalize_column_name(name: str) -> str:
    return "".join(ch.lower() for ch in str(name) if ch.isalnum())


def find_matching_column(df: pd.DataFrame, aliases: list[str]) -> str | None:
    alias_set = {normalize_column_name(alias) for alias in aliases}
    for column in df.columns:
        if normalize_column_name(column) in alias_set:
            return column
    return None


def score_delivery(reliability_pct: float) -> int:
    if reliability_pct >= 90:
        return 100
    if reliability_pct >= 75:
        return 75
    if reliability_pct >= 60:
        return 50
    return 30


def score_quality(defect_increase_pct: float) -> int:
    if defect_increase_pct <= 0:
        return 100
    if defect_increase_pct <= 10:
        return 75
    if defect_increase_pct <= 20:
        return 50
    return 30


def score_inventory(spillover_pct: float) -> int:
    if spillover_pct <= 10:
        return 100
    if spillover_pct <= 20:
        return 75
    if spillover_pct <= 30:
        return 50
    return 30


def score_productivity(velocity_change_pct: float) -> int:
    if velocity_change_pct >= 0:
        return 100
    if velocity_change_pct >= -10:
        return 75
    if velocity_change_pct >= -20:
        return 50
    return 30


def normalize_people_score(morale_score: int) -> int:
    people_map = {5: 100, 4: 80, 3: 60, 2: 40, 1: 20}
    return people_map.get(int(morale_score), 60)


def get_health_and_action(final_score: float) -> tuple[str, str]:
    if final_score >= 85:
        return "Excellent", "Start-Stop-Continue"
    if final_score >= 70:
        return "Good", "Metrics Retro"
    if final_score >= 50:
        return "Moderate Risk", "Sprint Detective"
    if final_score >= 30:
        return "High Risk", "5 Whys"
    return "Critical", "5 Whys + Fishbone"


def get_default_team_morale() -> int:
    if "last_mood" in st.session_state:
        try:
            return max(1, min(5, int(st.session_state["last_mood"])))
        except Exception:
            pass

    mood_history = st.session_state.get("mood_history", [])
    if mood_history:
        try:
            avg_value = int(round(sum(float(v) for v in mood_history) / len(mood_history)))
            return max(1, min(5, avg_value))
        except Exception:
            pass

    return 3


def get_mood_score_by_sprint_name() -> dict[str, float]:
    mood_records = get_sheet_records(MOOD_WORKSHEET_NAME, rows=500, cols=10)
    if not mood_records:
        return {}

    mood_df = pd.DataFrame(mood_records)
    required_cols = {"PI or Sprint Name", "Average Mood Score"}
    if not required_cols.issubset(set(mood_df.columns)):
        return {}

    mood_df = mood_df.copy()
    mood_df["PI or Sprint Name"] = mood_df["PI or Sprint Name"].astype(str).str.strip()
    mood_df["Average Mood Score"] = pd.to_numeric(mood_df["Average Mood Score"], errors="coerce")
    mood_df = mood_df.dropna(subset=["Average Mood Score"])
    mood_df = mood_df[mood_df["PI or Sprint Name"] != ""]

    if mood_df.empty:
        return {}

    grouped = mood_df.groupby("PI or Sprint Name", as_index=False)["Average Mood Score"].mean()
    return {
        str(row["PI or Sprint Name"]): float(row["Average Mood Score"])
        for _, row in grouped.iterrows()
    }


def prepare_retro_health_dataframe(source_df: pd.DataFrame) -> tuple[pd.DataFrame | None, list[str]]:
    sprint_col = find_matching_column(source_df, ["Sprint Name", "Sprint"])
    committed_col = find_matching_column(source_df, ["Committed SP", "Committed"])
    completed_col = find_matching_column(source_df, ["Completed SP", "Completed"])
    defects_col = find_matching_column(source_df, ["Defects #", "Defects", "Defect", "Defect Count"])

    missing_fields: list[str] = []
    if not sprint_col:
        missing_fields.append("Sprint Name")
    if not committed_col:
        missing_fields.append("Committed SP")
    if not completed_col:
        missing_fields.append("Completed SP")
    if not defects_col:
        missing_fields.append("Defects #")

    if missing_fields:
        return None, missing_fields

    retro_df = pd.DataFrame(
        {
            "Sprint Name": source_df[sprint_col].astype(str).str.strip(),
            "Committed SP": pd.to_numeric(source_df[committed_col], errors="coerce").fillna(0),
            "Completed SP": pd.to_numeric(source_df[completed_col], errors="coerce").fillna(0),
            "Defects #": pd.to_numeric(source_df[defects_col], errors="coerce").fillna(0),
        }
    )

    retro_df = retro_df[retro_df["Sprint Name"] != ""].copy()
    retro_df = retro_df.reset_index(drop=True)

    reliability_pct = []
    spillover_pct = []
    defect_increase_pct = []
    velocity_change_pct = []

    previous_defects = None
    previous_velocity = None

    for _, row in retro_df.iterrows():
        committed = float(row["Committed SP"])
        completed = float(row["Completed SP"])
        defects = float(row["Defects #"])

        reliability = (completed / committed) * 100 if committed > 0 else 0.0
        spillover = ((committed - completed) / committed) * 100 if committed > 0 else 0.0

        if previous_defects is None:
            defect_increase = 0.0
        elif previous_defects == 0:
            defect_increase = 0.0
        else:
            defect_increase = ((defects - previous_defects) / previous_defects) * 100

        if previous_velocity is None:
            velocity_change = 0.0
        elif previous_velocity == 0:
            velocity_change = 0.0
        else:
            velocity_change = ((completed - previous_velocity) / previous_velocity) * 100

        reliability_pct.append(reliability)
        spillover_pct.append(spillover)
        defect_increase_pct.append(defect_increase)
        velocity_change_pct.append(velocity_change)

        previous_defects = defects
        previous_velocity = completed

    retro_df["Reliability %"] = reliability_pct
    retro_df["Spillover %"] = spillover_pct
    retro_df["Defect Increase %"] = defect_increase_pct
    retro_df["Velocity Change %"] = velocity_change_pct

    retro_df["Delivery Score"] = retro_df["Reliability %"].apply(score_delivery)
    retro_df["Quality Score"] = retro_df["Defect Increase %"].apply(score_quality)
    retro_df["Inventory Score"] = retro_df["Spillover %"].apply(score_inventory)
    retro_df["Productivity Score"] = retro_df["Velocity Change %"].apply(score_productivity)

    return retro_df, []


def pick_weakest_category(category_scores: dict[str, float]) -> str:
    min_score = min(category_scores.values())
    lowest_categories = [name for name, score in category_scores.items() if score == min_score]

    for category in RETRO_PRIORITY_ORDER:
        if category in lowest_categories:
            return category

    return lowest_categories[0]


def get_ai_retro_recommendation(category_scores: dict[str, float]) -> dict[str, str]:
    selected_category = pick_weakest_category(category_scores)
    recommended_retro = RETRO_CATEGORY_MAP[selected_category]
    reason = RETRO_REASON_MAP[selected_category]

    sorted_scores = sorted(category_scores.values())
    if len(sorted_scores) < 2:
        confidence = "High"
    else:
        gap = sorted_scores[1] - sorted_scores[0]
        confidence = "High" if gap > 10 else "Medium"

    return {
        "focus_area": selected_category,
        "recommended_retro": recommended_retro,
        "reason": reason,
        "confidence": confidence,
    }


def get_retro_health_analysis() -> dict | None:
    sprint_df = st.session_state.get("sprint_df", pd.DataFrame())
    if sprint_df.empty:
        return None

    game_df = sprint_df.copy()
    if "Defects #" not in game_df.columns:
        game_df["Defects #"] = 0
    game_df = game_df.rename(
        columns={
            "Sprint": "Sprint Name",
            "Committed": "Committed SP",
            "Completed": "Completed SP",
        }
    )

    mood_sheet_error = ""
    try:
        mood_by_sprint = get_mood_score_by_sprint_name()
    except Exception as error:
        mood_by_sprint = {}
        mood_sheet_error = str(error)

    retro_df, missing_fields = prepare_retro_health_dataframe(game_df)
    if retro_df is None:
        return {
            "error": "Input data is missing required fields: " + ", ".join(missing_fields),
            "mood_sheet_error": mood_sheet_error,
            "mood_by_sprint": mood_by_sprint,
        }

    retro_df = retro_df.tail(6).copy()
    fallback_people_score = normalize_people_score(get_default_team_morale())

    raw_people_mood = retro_df["Sprint Name"].map(mood_by_sprint)
    carried_people_mood = raw_people_mood.ffill()
    missing_after_carry = carried_people_mood.isna()

    retro_df["People Mood (1-5)"] = carried_people_mood.fillna(float(get_default_team_morale()))
    retro_df["People Mood Source"] = "Direct mood match"
    retro_df.loc[raw_people_mood.isna(), "People Mood Source"] = "Previous sprint mood"
    retro_df.loc[missing_after_carry, "People Mood Source"] = "Default mood fallback"

    retro_df["People Mood (1-5)"] = retro_df["People Mood (1-5)"].clip(lower=1, upper=5)
    retro_df["People Score"] = retro_df["People Mood (1-5)"].apply(
        lambda value: normalize_people_score(int(round(float(value))))
    )
    if retro_df["People Score"].isna().all():
        retro_df["People Score"] = fallback_people_score

    retro_df["Final Score"] = (
        retro_df["Delivery Score"] * RETRO_CATEGORY_WEIGHTS["Delivery"]
        + retro_df["Quality Score"] * RETRO_CATEGORY_WEIGHTS["Quality"]
        + retro_df["Inventory Score"] * RETRO_CATEGORY_WEIGHTS["Inventory"]
        + retro_df["Productivity Score"] * RETRO_CATEGORY_WEIGHTS["Productivity"]
        + retro_df["People Score"] * RETRO_CATEGORY_WEIGHTS["People"]
    )

    category_scores = {
        "Delivery": float(retro_df["Delivery Score"].mean()),
        "Quality": float(retro_df["Quality Score"].mean()),
        "Inventory": float(retro_df["Inventory Score"].mean()),
        "Productivity": float(retro_df["Productivity Score"].mean()),
        "People": float(retro_df["People Score"].mean()),
    }
    ai_reco = get_ai_retro_recommendation(category_scores)

    return {
        "retro_df": retro_df,
        "category_scores": category_scores,
        "ai_reco": ai_reco,
        "sprint_count": len(retro_df),
        "mood_sheet_error": mood_sheet_error,
        "mood_by_sprint": mood_by_sprint,
    }


apply_pending_session_resets()
retro_analysis = get_retro_health_analysis()
if retro_analysis and "ai_reco" in retro_analysis:
    st.session_state["spin_recommended_retro"] = str(retro_analysis["ai_reco"]["recommended_retro"])


# Create Tabs
tab1, tab2, tab3, tab4, tab5, tab6, tab7 = st.tabs([
    "😊 Mood",
    "📊 Sprint Insights",
    "🧠 AI Retro Game",
    "🎡 Spin Wheel",
    "👑 Dashboard",
    "📌 Action Tracker",
    "🐟 Fishbone Analysis"
])

with tab1:
    show_flash_message("mood")
    st.subheader("Team Mood Check")

    mood_meta_col1, mood_meta_col2 = st.columns(2)
    team_name = mood_meta_col1.text_input("Team Name(s)", key="mood_team_name_input")
    sprint_or_pi_name = mood_meta_col2.text_input("PI or Sprint Name", key="mood_sprint_name_input")

    st.write("Select your mood:")

    col1, col2, col3, col4, col5 = st.columns(5)

    moods = {
        "😡": 1,
        "😟": 2,
        "😐": 3,
        "😊": 4,
        "🚀": 5
    }

    selected_mood = None

    for i, (emoji, value) in enumerate(moods.items()):
        if [col1, col2, col3, col4, col5][i].button(emoji):
            selected_mood = value
            st.session_state["last_mood"] = value

    if "mood_history" not in st.session_state:
        st.session_state["mood_history"] = []

    if selected_mood is not None:
        st.session_state["mood_history"].append(selected_mood)

    average_mood = 0.0
    mood_status = ""

    if "last_mood" in st.session_state:
        mood = st.session_state["last_mood"]
        if mood <= 2:
            st.error("⚠️ Team morale is low")
        elif mood == 3:
            st.warning("🙂 Neutral mood")
        else:
            st.success("🚀 Positive team energy")

    if st.session_state["mood_history"]:
        average_mood = sum(st.session_state["mood_history"]) / len(st.session_state["mood_history"])
        mood_status = get_mood_status(average_mood)
        st.metric("Average Mood", f"{average_mood:.2f}")

        if average_mood < 2.5:
            st.error("Team is struggling 😟")
        elif average_mood < 4:
            st.warning("Team is okay but needs improvement")
        else:
            st.success("Team is performing great 🚀")

    if st.button("Save Mood Data", key="save_mood_data_button"):
        if not team_name.strip() or not sprint_or_pi_name.strip():
            st.warning("Please enter Team Name(s) and PI or Sprint Name.")
        elif not st.session_state["mood_history"]:
            st.warning("Please select at least one mood before saving.")
        else:
            try:
                save_mood_data_to_google_sheet(
                    team_name.strip(),
                    sprint_or_pi_name.strip(),
                    average_mood,
                    mood_status,
                )
                mark_sync_event("Saved mood data")
                st.session_state["mood_history"] = []
                st.session_state.pop("last_mood", None)
                clear_session_keys("mood_team_name_input", "mood_sprint_name_input")
                set_flash_message("mood", "success", "Mood data saved successfully!")
                st.rerun()
            except Exception as error:
                st.error(f"Unable to save mood data: {error}")

with tab2:
    show_flash_message("sprint")
    st.subheader("Sprint Insights Tracker")

    sprint_columns = ["Sprint", "Committed", "Completed", "Scope Added", "Defects #", "Spill Over"]

    # Initialize storage
    if "sprint_df" not in st.session_state:
        st.session_state.sprint_df = pd.DataFrame(
            columns=sprint_columns
        )
        st.session_state.sprint_df = ensure_spill_over_column(st.session_state.sprint_df)

    # Always recompute and reorder columns before rendering so Spill Over is visible.
    st.session_state.sprint_df = ensure_spill_over_column(st.session_state.sprint_df)
    st.session_state.sprint_df = st.session_state.sprint_df.reindex(columns=sprint_columns)

    # ------------------ OPTION 1: CSV / Excel Upload ------------------
    st.write("### Upload CSV or Excel")
    uploaded_file = st.file_uploader("Upload Sprint Data (CSV, XLSX, XLS)", type=["csv", "xlsx", "xls"])

    if uploaded_file:
        try:
            uploaded_name = uploaded_file.name.lower()
            if uploaded_name.endswith(".csv"):
                df_uploaded = pd.read_csv(uploaded_file)
            else:
                df_uploaded = pd.read_excel(uploaded_file)
        except Exception as error:
            st.error(f"Unable to read uploaded file: {error}")
        else:
            required_cols = ["Sprint", "Committed", "Completed", "Scope Added"]
            if all(col in df_uploaded.columns for col in required_cols):
                if "Defects #" not in df_uploaded.columns:
                    df_uploaded["Defects #"] = 0
                st.session_state.sprint_df = ensure_spill_over_column(df_uploaded.tail(6)).reindex(columns=sprint_columns)
                st.success("File uploaded successfully!")
            else:
                st.error("Uploaded file must contain: Sprint, Committed, Completed, Scope Added")

    # ------------------ OPTION 2: Manual Entry ------------------
    st.write("### Add Sprint Data Manually")

    sprint_name = st.text_input("Sprint Name", key="sprint_name_input")
    committed = st.number_input("Committed Story Points", min_value=0, key="committed_input")
    completed = st.number_input("Completed Story Points", min_value=0, key="completed_input")
    scope_added = st.number_input("Scope Added", min_value=0, key="scope_added_input")
    defects = st.number_input("Defects #", min_value=0, key="defects_input")

    if st.button("Add Sprint"):
        if sprint_name:
            new_row = pd.DataFrame([{
                "Sprint": sprint_name,
                "Committed": committed,
                "Completed": completed,
                "Scope Added": scope_added,
                "Defects #": defects,
            }])

            st.session_state.sprint_df = pd.concat(
                [st.session_state.sprint_df, new_row],
                ignore_index=True
            ).tail(6)
            st.session_state.sprint_df = ensure_spill_over_column(st.session_state.sprint_df).reindex(columns=sprint_columns)
            clear_session_keys("sprint_name_input", "committed_input", "completed_input", "scope_added_input", "defects_input")
            set_flash_message("sprint", "success", "Sprint added successfully!")
            st.rerun()

    # ------------------ GOOGLE SHEETS ------------------
    st.write("### Google Sheets")
    sheet_col1, sheet_col2 = st.columns(2)

    if sheet_col1.button("Test Sheet"):
        try:
            workbook = get_google_workbook()
            st.success(f"Connected successfully to {workbook.title}!")
        except Exception as error:
            st.error(f"Google Sheets connection failed: {error}")

    if sheet_col2.button("Save Sprint Data"):
        try:
            save_sprint_data_to_google_sheet(st.session_state.sprint_df, sprint_columns)
            mark_sync_event("Saved sprint data")
            set_flash_message("sprint", "success", "Sprint data saved to Google Sheet successfully!")
            st.rerun()
        except Exception as error:
            st.error(f"Unable to save sprint data: {error}")

    # ------------------ EDITABLE TABLE ------------------
    st.write("### Edit Sprint Data")

    edited_df = st.data_editor(
        st.session_state.sprint_df,
        num_rows="dynamic",
        column_order=sprint_columns,
        disabled=["Spill Over"],
        use_container_width=True
    )

    st.session_state.sprint_df = ensure_spill_over_column(edited_df).reindex(columns=sprint_columns)

    # ------------------ DELETE OPTION ------------------
    st.write("### Delete Sprint")

    if not st.session_state.sprint_df.empty:
        sprint_to_delete = st.selectbox(
            "Select sprint to delete",
            st.session_state.sprint_df["Sprint"]
        )

        if st.button("Delete Sprint"):
            st.session_state.sprint_df = st.session_state.sprint_df[
                st.session_state.sprint_df["Sprint"] != sprint_to_delete
            ]
            st.session_state.sprint_df = ensure_spill_over_column(st.session_state.sprint_df).reindex(columns=sprint_columns)
            st.success("Sprint deleted!")

    # ------------------ METRICS ------------------
    df = st.session_state.sprint_df

    if not df.empty:
        st.write("### Key Metrics")

        total_committed = df["Committed"].sum()
        total_completed = df["Completed"].sum()
        total_scope = df["Scope Added"].sum()

        avg_velocity = df["Completed"].mean()
        predictability = (total_completed / total_committed) * 100 if total_committed > 0 else 0
        scope_change = (total_scope / total_committed) * 100 if total_committed > 0 else 0
        avg_spill_over_percentage = df["Spill Over"].sum() / len(df) if len(df) > 0 else 0

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Avg Velocity", f"{avg_velocity:.2f}")
        col2.metric("Predictability %", f"{predictability:.2f}%")
        col3.metric("Scope Change %", f"{scope_change:.2f}%")
        col4.metric("Average Spill Over %", f"{avg_spill_over_percentage:.2f}")

        # ------------------ TREND ------------------
        st.write("### Velocity Trend")
        st.line_chart(df.set_index("Sprint")[["Completed"]])

        st.write("### Spill Over Trend")
        st.line_chart(df.set_index("Sprint")[["Spill Over"]])

        # ------------------ INSIGHTS ------------------
        st.write("### Insights")

        if predictability < 70:
            st.error("⚠️ Low predictability → Overcommitment / dependencies")
        elif predictability < 90:
            st.warning("⚠️ Moderate predictability")
        else:
            st.success("✅ Strong delivery")

        if scope_change > 20:
            st.error("⚠️ High scope creep")
        else:
            st.success("✅ Stable scope")

with tab3:
    show_flash_message("retro_game")
    st.subheader("🧠 AI Retro Game")

    st.write("### Category To Retro Map")
    retro_map_rows = [
        ("Delivery", "5 Whys"),
        ("Quality", "[Fishbone](#fishbone-analysis)"),
        ("Inventory", "Sprint Detective"),
        ("Productivity", "Metrics Retro"),
        ("People", "Mad-Sad-Glad"),
    ]

    retro_map_markdown = "| Category | Retro |\n|---|---|\n" + "\n".join(
        f"| {category} | {retro} |" for category, retro in retro_map_rows
    )
    st.markdown(retro_map_markdown)
    st.caption("If the link does not jump in your browser, click the 🐟 Fishbone Analysis tab above.")

    if not retro_analysis:
        st.info("Add Sprint Insights data to calculate average category scores and AI retro recommendation.")
    elif "error" in retro_analysis:
        st.warning(str(retro_analysis["error"]))
    else:
        category_scores = dict(retro_analysis["category_scores"])
        ai_reco = dict(retro_analysis["ai_reco"])
        sprint_count = int(retro_analysis["sprint_count"])
        retro_df = retro_analysis["retro_df"]
        mood_sheet_error = str(retro_analysis.get("mood_sheet_error", ""))
        mood_by_sprint = retro_analysis.get("mood_by_sprint", {})

        if mood_by_sprint:
            st.caption("People metric uses Mood Tracker matched by sprint name, then previous sprint mood for missing values.")
        elif mood_sheet_error:
            st.caption(f"People metric fallback used because Mood Tracker read failed: {mood_sheet_error}")

        st.write(f"### Category Scores (Average of {sprint_count} Sprints)")
        category_df = pd.DataFrame(
            {
                "Category": list(category_scores.keys()),
                "Score": [round(value, 2) for value in category_scores.values()],
            }
        )
        st.dataframe(category_df, use_container_width=True)

        st.write("### AI Recommendation")
        reco_col1, reco_col2 = st.columns(2)
        reco_col1.metric("Focus Area", ai_reco["focus_area"])
        reco_col2.metric("Confidence", ai_reco["confidence"])
        st.success(f"Recommended Retro: {ai_reco['recommended_retro']}")
        st.info(f"Reason: {ai_reco['reason']}")

        st.write("### Sprint KPI View")
        display_columns = [
            "Sprint Name",
            "Committed SP",
            "Completed SP",
            "Defects #",
            "Reliability %",
            "Spillover %",
            "Defect Increase %",
            "Velocity Change %",
            "People Mood (1-5)",
            "People Mood Source",
        ]
        st.dataframe(retro_df[display_columns], use_container_width=True)

with tab4:
    show_flash_message("spin")
    st.subheader("🎡 Spin the Retro Wheel")

    try:
        config_sheet = get_or_create_worksheet(CONFIG_WORKSHEET_NAME, rows=20, cols=5)
        response_sheet = get_or_create_worksheet(RESPONSES_WORKSHEET_NAME, rows=500, cols=10)

        if "question_timer_seconds" not in st.session_state:
            st.session_state["question_timer_seconds"] = 60
        if "question_timer_reset_count" not in st.session_state:
            st.session_state["question_timer_reset_count"] = 0

        if "spin_count" not in st.session_state:
            st.session_state["spin_count"] = 0
        if "current_spin_question" not in st.session_state:
            st.session_state["current_spin_question"] = None
        if "used_questions" not in st.session_state:
            st.session_state["used_questions"] = []

        active_retro = str(st.session_state.get("spin_recommended_retro", "")).strip()
        active_questions = RETRO_QUESTION_MAP.get(active_retro, DEFAULT_SPIN_QUESTIONS)
        question_set_key = f"retro::{active_retro or 'default'}"

        if st.session_state.get("spin_question_set_key") != question_set_key:
            st.session_state["spin_question_set_key"] = question_set_key
            st.session_state["spin_count"] = 0
            st.session_state["used_questions"] = []
            st.session_state["current_spin_question"] = None

        # Check if all spins are complete
        spins_target = len(active_questions)
        spins_complete = st.session_state["spin_count"] >= spins_target

        if active_retro:
            st.caption(f"Dynamic mode: {active_retro} questions")
        else:
            st.caption("Dynamic mode: default retro questions")

        timer_col1, timer_col2 = st.columns([2, 1])
        timer_col1.number_input(
            "Timer per question (seconds)",
            min_value=0,
            step=15,
            key="question_timer_seconds",
            help="Set 0 to disable the timer.",
        )
        if timer_col2.button("Reset Timer", key="reset_question_timer_button"):
            st.session_state["question_timer_reset_count"] += 1
            st.rerun()
        
        # Disable spin button after 7 spins
        spin_button = st.button("🎯 Spin the Wheel", disabled=spins_complete)

        if spin_button and not spins_complete:
            # Increment spin count
            st.session_state["spin_count"] += 1
            is_last_spin = st.session_state["spin_count"] >= spins_target
            
            # Get remaining unused questions
            remaining_questions = [q for q in active_questions if q not in st.session_state["used_questions"]]
            
            # If all questions used, reset the list.
            if not remaining_questions:
                remaining_questions = active_questions
                st.session_state["used_questions"] = []
            
            # Pick final question from remaining
            final_question = random.choice(remaining_questions)
            st.session_state["used_questions"].append(final_question)
            
            # Generate and inject audio (autoplay during spinner)
            audio_data = generate_spin_sound()
            audio_base64 = base64.b64encode(audio_data).decode()
            
            st.markdown(
                f'<audio autoplay><source src="data:audio/wav;base64,{audio_base64}" type="audio/wav"></audio>',
                unsafe_allow_html=True
            )
            
            # Show spinner while audio plays
            with st.spinner("🎡 Spinning the wheel..."):
                time.sleep(1.5)
            
            # Save question to sheet
            config_sheet.update_acell("A1", final_question)
            st.session_state["current_spin_question"] = final_question
            st.session_state["question_timer_reset_count"] += 1
            clear_google_sheet_read_cache()
            
            # Show balloons only on last spin.
            if is_last_spin:
                st.balloons()
            
            # Rerun to show updated question
            st.rerun()

        # Display spin completion status
        if spins_complete:
            st.success(f"✅ All {spins_target} questions completed! Great job! 🎉")

        # Display the current question persistently until next spin
        current_question = st.session_state.get("current_spin_question") or get_sheet_cell_value(
            CONFIG_WORKSHEET_NAME,
            "A1",
            rows=20,
            cols=5,
        )

        if current_question:
            st.write("### 📌 Current Question")
            st.success(current_question)
            render_question_timer(
                current_question,
                int(st.session_state.get("question_timer_seconds", 0)),
                str(st.session_state.get("question_timer_reset_count", 0)),
            )
            
            # Show spin count indicator with progress
            progress_text = f"Question {st.session_state['spin_count']}/{spins_target}"
            if st.session_state["spin_count"] >= spins_target:
                progress_text += " ✨ FINAL!"
            st.caption(f"🎡 {progress_text}")

            if not spins_complete:  # Only show input if spins not complete
                user_input = st.text_area("💬 Your response", key=f"response_{current_question}")

                if st.button("Submit Response"):
                    if user_input.strip():
                        existing_header = get_sheet_row_values(
                            RESPONSES_WORKSHEET_NAME,
                            1,
                            rows=500,
                            cols=10,
                        )
                        expected_header = ["Timestamp", "Question", "Response"]

                        if existing_header != expected_header:
                            response_sheet.clear()
                            response_sheet.append_row(expected_header)

                        response_sheet.append_row([
                            datetime.now().isoformat(),
                            current_question,
                            user_input.strip(),
                        ])
                        clear_google_sheet_read_cache()
                        mark_sync_event("Saved spin wheel response")
                        clear_session_keys(f"response_{current_question}")
                        set_flash_message("spin", "success", "Response submitted successfully!")
                        st.rerun()
                    else:
                        st.warning("Please add something")
            else:
                st.info("🎊 All responses collected! Session complete.")
        
    except Exception as error:
        st.error(f"Unable to load spin wheel data: {error}")

with tab5:
    show_flash_message("dashboard")
    st.subheader("👑 Scrum Master Dashboard")

    sync_col, action_col = st.columns([5, 1])
    last_sync_time = st.session_state.get("last_sync_time", "Never")
    last_sync_event = st.session_state.get("last_sync_event", "No sync yet")
    sync_col.caption(f"Last synced on: {last_sync_time} | {last_sync_event}")

    if action_col.button("🔄 Refresh", key="dashboard_refresh_button"):
        for key in ["ai_last_question", "ai_chat_history", "ai_clustered_data"]:
            if key in st.session_state:
                del st.session_state[key]
        st.rerun()

    try:
        config_sheet = get_or_create_worksheet(CONFIG_WORKSHEET_NAME, rows=20, cols=5)
        response_sheet = get_or_create_worksheet(RESPONSES_WORKSHEET_NAME, rows=500, cols=10)
        discussion_sheet = get_or_create_worksheet("Discussions", rows=500, cols=5)

        # Load all response rows from Google Sheets.
        data = get_sheet_records(RESPONSES_WORKSHEET_NAME, rows=500, cols=10)
        df = pd.DataFrame(data)

        if df.empty:
            st.warning("No responses yet")
        else:
            st.write("### 🔍 Filter by Question")
            questions = df["Question"].dropna().unique()

            if len(questions) == 0:
                st.info("No question data found in responses yet.")
            else:
                current_question = st.session_state.get("current_spin_question") or get_sheet_cell_value(
                    CONFIG_WORKSHEET_NAME,
                    "A1",
                    rows=20,
                    cols=5,
                )
                default_index = 0
                if current_question and current_question in questions:
                    default_index = list(questions).index(current_question)

                selected_question = st.selectbox("Select Question", questions, index=default_index)
                filtered_df = df[df["Question"] == selected_question]

                st.write("### 🧾 Responses for Selected Question")
                st.dataframe(filtered_df, use_container_width=True)

                st.write("### 📈 Insights")
                col1, col2 = st.columns(2)
                col1.metric("Total Responses", len(df))
                col2.metric("Unique Questions", df["Question"].nunique())

                st.write("### 💬 Discussion View")
                if filtered_df.empty:
                    st.info("No responses for this question yet")
                else:
                    for _, row in filtered_df.iterrows():
                        st.write(f"🟢 {row['Response']}")
                        st.write("---")

                # ---- Capture Discussion Points ----
                st.write("### 🧠 Capture Discussion Points")
                discussion_input = st.text_area("Summarize team discussion for this question", key=f"discussion_{selected_question}")

                if st.button("Save Discussion"):
                    if discussion_input.strip():
                        # Ensure header row exists
                        existing_header = get_sheet_row_values(
                            "Discussions",
                            1,
                            rows=500,
                            cols=5,
                        )
                        if existing_header != ["Question", "Discussion"]:
                            discussion_sheet.clear()
                            discussion_sheet.append_row(["Question", "Discussion"])
                        discussion_sheet.append_row([selected_question, discussion_input.strip()])
                        clear_google_sheet_read_cache()
                        mark_sync_event("Saved discussion point")
                        clear_session_keys(f"discussion_{selected_question}")
                        set_flash_message("dashboard", "success", "Discussion saved successfully!")
                        st.rerun()
                    else:
                        st.warning("Please enter a discussion summary before saving.")

                # ---- Show Saved Discussions ----
                st.write("### 📌 Saved Discussion Points")
                discussion_data = get_sheet_records("Discussions", rows=500, cols=5)
                filtered_discussion = pd.DataFrame(columns=["Question", "Discussion"])
                if discussion_data:
                    discussion_df = pd.DataFrame(discussion_data)
                    filtered_discussion = discussion_df[
                        discussion_df["Question"] == selected_question
                    ]
                    if filtered_discussion.empty:
                        st.info("No discussion points saved for this question yet.")
                    else:
                        st.dataframe(filtered_discussion[["Discussion"]], use_container_width=True)
                else:
                    st.info("No discussion points saved yet.")

                # ---- AI Analysis: Team Inputs -> Clustering -> Summary -> Chat Follow-ups ----
                st.write("### 🤖 AI Scrum Master")

                if "ai_chat_history" not in st.session_state:
                    st.session_state.ai_chat_history = []
                if "ai_clustered_data" not in st.session_state:
                    st.session_state.ai_clustered_data = ""
                if "ai_last_question" not in st.session_state:
                    st.session_state.ai_last_question = None

                # Reset conversation context when question changes.
                if st.session_state.ai_last_question != selected_question:
                    st.session_state.ai_chat_history = []
                    st.session_state.ai_clustered_data = ""
                    st.session_state.ai_last_question = selected_question

                api_key, key_source, secret_keys = get_openai_api_key()
                if not api_key:
                    st.error("OpenAI key is missing. Add OPENAI_API_KEY in Streamlit secrets and restart the app.")
                    st.caption(
                        f"Diagnostics: key_source={key_source}; top_level_secrets={', '.join(secret_keys) if secret_keys else 'none'}"
                    )
                else:
                    sprint_df = st.session_state.get("sprint_df", pd.DataFrame())

                    sprint_summary = ""
                    if not sprint_df.empty:
                        sprint_summary = "Sprint,Committed,Completed,ScopeAdded\n"
                        for _, srow in sprint_df.tail(6).iterrows():
                            sprint_summary += (
                                f"{srow.get('Sprint', '?')},"
                                f"{int(srow.get('Committed', 0) or 0)},"
                                f"{int(srow.get('Completed', 0) or 0)},"
                                f"{int(srow.get('Scope Added', 0) or 0)}\n"
                            )

                    discussion_text = ""
                    if not filtered_discussion.empty:
                        seen = set()
                        unique_lines = []
                        for line in filtered_discussion["Discussion"].dropna().astype(str):
                            stripped = line.strip()
                            if stripped and stripped not in seen:
                                seen.add(stripped)
                                unique_lines.append(stripped)
                        discussion_text = "\n".join(unique_lines)[:3000]

                    system_prompt = (
                        "You are an experienced Scrum Master assistant. "
                        "Use ONLY the provided data. No assumptions. If data is insufficient, say 'Not enough data'.\n\n"
                        f"Selected Question: {selected_question}\n"
                        f"Sprint Data:\n{sprint_summary or 'none'}\n"
                        f"Team Discussions:\n{discussion_text or 'none'}"
                    )

                    def generate_clustered_summary(client: OpenAI) -> str:
                        cluster_prompt = (
                            "Cluster similar discussion responses.\n"
                            "Output:\n"
                            "🔹 Theme: <name>\n- Description: ...\n- Mentions: <count>\n\n"
                            "⚠️ Key Problems:\n- ...\n\n"
                            "✅ Positive Signals:\n- ..."
                        )

                        response = client.chat.completions.create(
                            model="gpt-4.1-mini",
                            messages=[
                                {"role": "system", "content": system_prompt},
                                {"role": "user", "content": cluster_prompt},
                            ],
                            temperature=0.2,
                            max_tokens=500,
                        )
                        return response.choices[0].message.content or "Not enough data"

                    if st.button("Generate Smart Insights", key=f"ai_generate_{selected_question}"):
                        if discussion_text.strip() == "":
                            st.warning("No discussion data available")
                        else:
                            try:
                                client = OpenAI(api_key=api_key)
                                with st.spinner("Generating clustered insights..."):
                                    clustered_output = generate_clustered_summary(client)

                                st.session_state.ai_clustered_data = clustered_output
                                st.session_state.ai_chat_history = [
                                    {"role": "assistant", "content": clustered_output}
                                ]
                                st.rerun()
                            except Exception as ai_error:
                                st.error(f"Unable to generate AI insights: {ai_error}")

                    # Display chat history
                    for msg in st.session_state.ai_chat_history:
                        with st.chat_message(msg["role"]):
                            st.markdown(msg["content"])

                    user_follow_up = st.chat_input(
                        "Ask follow-up (e.g., top blockers, trimmed actions, owner-wise tasks)",
                        key=f"ai_chat_input_{selected_question}",
                    )

                    if user_follow_up:
                        st.session_state.ai_chat_history.append(
                            {"role": "user", "content": user_follow_up}
                        )

                        history = st.session_state.ai_chat_history[-6:]
                        message_payload: list[dict[str, str]] = [
                            {
                                "role": "system",
                                "content": system_prompt
                                + "\n\nClustered Insights:\n"
                                + str(st.session_state.ai_clustered_data or "none"),
                            }
                        ]
                        for entry in history:
                            role = str(entry.get("role", "user"))
                            content = str(entry.get("content", ""))
                            message_payload.append({"role": role, "content": content})

                        try:
                            client = OpenAI(api_key=api_key)
                            with st.spinner("Generating follow-up insight..."):
                                response = client.chat.completions.create(
                                    model="gpt-4.1-mini",
                                    messages=message_payload,  # type: ignore[arg-type]
                                    temperature=0.2,
                                    max_tokens=450,
                                )

                            reply = response.choices[0].message.content or "Not enough data"
                            st.session_state.ai_chat_history.append(
                                {"role": "assistant", "content": reply}
                            )
                            st.rerun()
                        except Exception as ai_error:
                            st.error(f"Unable to generate follow-up insight: {ai_error}")

                    if st.button("🧹 Clear Chat", key=f"ai_clear_{selected_question}"):
                        st.session_state.ai_chat_history = []
                        st.session_state.ai_clustered_data = ""
                        st.rerun()
    except Exception as error:
        st.error(f"Unable to load Scrum Master dashboard: {error}")

with tab6:
    show_flash_message("action")
    st.subheader("📌 Action Tracker")

    try:
        main_sheet = get_google_workbook()
        try:
            action_sheet = main_sheet.worksheet(ACTION_WORKSHEET_NAME)
        except gspread.WorksheetNotFound:
            action_sheet = main_sheet.add_worksheet(title=ACTION_WORKSHEET_NAME, rows=500, cols=10)

        if "action_sheet_schema_checked" not in st.session_state:
            ensure_action_sheet_schema(action_sheet)
            st.session_state["action_sheet_schema_checked"] = True

        action_data = get_sheet_records(ACTION_WORKSHEET_NAME, rows=500, cols=10)
        action_df = normalize_action_dataframe(pd.DataFrame(action_data))

        if action_df.empty:
            st.info("No actions yet")
        else:
            normalized_priority = action_df["Priority"].astype(str).str.strip().str.title()
            high_count = int((normalized_priority == "High").sum())
            medium_count = int((normalized_priority == "Medium").sum())
            low_count = int((normalized_priority == "Low").sum())
            ai_count = int((action_df["Source"] == AI_ACTION_SOURCE).sum())

            st.write("### 📊 Priority Summary")
            summary_col1, summary_col2, summary_col3, summary_col4 = st.columns(4)
            summary_col1.metric("High", high_count)
            summary_col2.metric("Medium", medium_count)
            summary_col3.metric("Low", low_count)
            summary_col4.metric("AI Generated", ai_count)

            st.write("### 🔎 Filter & Sort")
            filter_col, source_col, sort_col = st.columns(3)

            selected_priority_filter = filter_col.selectbox(
                "Priority Filter",
                ["All", "High", "Medium", "Low"],
                key="priority_filter",
            )
            selected_source_filter = source_col.selectbox(
                "Source Filter",
                ["All", TEAM_ACTION_SOURCE, AI_ACTION_SOURCE],
                key="source_filter",
            )
            selected_sort = sort_col.selectbox(
                "Sort By",
                ["Priority (High to Low)", "Priority (Low to High)", "Action (A-Z)", "Action (Z-A)"],
                key="priority_sort",
            )

            filtered_actions_df = action_df.copy()
            filtered_actions_df["Priority"] = (
                filtered_actions_df["Priority"].astype(str).str.strip().str.title()
            )

            if selected_priority_filter != "All":
                filtered_actions_df = filtered_actions_df[
                    filtered_actions_df["Priority"] == selected_priority_filter
                ]

            if selected_source_filter != "All":
                filtered_actions_df = filtered_actions_df[
                    filtered_actions_df["Source"] == selected_source_filter
                ]

            priority_rank = {"High": 0, "Medium": 1, "Low": 2}
            filtered_actions_df["_priority_rank"] = filtered_actions_df["Priority"].map(priority_rank).fillna(3)

            if selected_sort == "Priority (High to Low)":
                filtered_actions_df = filtered_actions_df.sort_values(
                    by=["_priority_rank", "Action"],
                    ascending=[True, True],
                )
            elif selected_sort == "Priority (Low to High)":
                filtered_actions_df = filtered_actions_df.sort_values(
                    by=["_priority_rank", "Action"],
                    ascending=[False, True],
                )
            elif selected_sort == "Action (A-Z)":
                filtered_actions_df = filtered_actions_df.sort_values(by="Action", ascending=True)
            else:
                filtered_actions_df = filtered_actions_df.sort_values(by="Action", ascending=False)

            filtered_actions_df = filtered_actions_df.drop(columns=["_priority_rank"])

            def highlight_priority(cell_value):
                value = str(cell_value).strip().lower()
                if value == "high":
                    return "background-color: #ffe4e6; color: #9f1239; font-weight: 700;"
                if value == "medium":
                    return "background-color: #fff7ed; color: #9a3412; font-weight: 700;"
                if value == "low":
                    return "background-color: #ecfdf5; color: #065f46; font-weight: 700;"
                return ""

            styled_df = filtered_actions_df.style.map(highlight_priority, subset=["Priority"])
            st.dataframe(styled_df, use_container_width=True)

            if filtered_actions_df.empty:
                st.info("No actions match the selected filter.")

        st.write("### ➕ Add Action Item")
        add_col1, add_col2 = st.columns(2)

        action_item = add_col1.text_input("Action Item", key="action_item_input")
        priority = add_col2.selectbox(
            "Priority",
            ["High", "Medium", "Low"],
            index=1,
            key="action_priority_input",
        )

        if st.button("Add Action", key="add_action_button"):
            if action_item.strip():
                action_sheet.append_row([action_item.strip(), priority, TEAM_ACTION_SOURCE])
                clear_google_sheet_read_cache()
                mark_sync_event("Added action item")
                st.session_state["action_priority_input"] = "Medium"
                clear_session_keys("action_item_input")
                set_flash_message("action", "success", "Action saved successfully!")
                st.rerun()
            else:
                st.warning("Please fill Action Item")

        st.write("### 🤖 Generate Actions from AI")

        ai_action_text = st.session_state.get("ai_actions_text", "")
        source_insights = st.session_state.get("ai_clustered_data", "") or st.session_state.get("clustered_data", "")

        if st.button("Generate AI Actions", key="generate_ai_actions_button"):
            api_key, key_source, secret_keys = get_openai_api_key()
            if not api_key:
                st.error("OpenAI key is missing. Add OPENAI_API_KEY in Streamlit secrets and restart the app.")
                st.caption(
                    f"Diagnostics: key_source={key_source}; top_level_secrets={', '.join(secret_keys) if secret_keys else 'none'}"
                )
            elif not str(source_insights).strip():
                st.warning("No AI insights found. Generate Smart Insights in Dashboard first.")
            else:
                prompt = f"""
Based on the following retrospective insights, generate actionable tasks.

Insights:
{source_insights}

Rules:
- Provide 3-5 actions
- Each must be specific and implementable
- Priority must be one of: High, Medium, Low
- Keep output concise

Output format:
Action Item | Priority
"""

                try:
                    client = OpenAI(api_key=api_key)
                    response = client.chat.completions.create(
                        model="gpt-4.1-mini",
                        messages=[{"role": "user", "content": prompt}],
                        temperature=0.2,
                    )

                    ai_action_text = (response.choices[0].message.content or "").strip()
                    st.session_state.ai_actions_text = ai_action_text
                except Exception as ai_error:
                    st.error(f"Unable to generate AI actions: {ai_error}")

        if ai_action_text:
            st.write("### Suggested Actions")

            parsed_ai_actions: list[dict[str, str]] = []
            lines = [ln.strip() for ln in ai_action_text.split("\n") if ln.strip()]

            for line in lines:
                if "|" not in line:
                    continue

                left, right = [part.strip() for part in line.split("|", 1)]
                if not left or not right:
                    continue

                # Skip markdown table headers and separator rows.
                if left.lower() in {"action item", "action", "task"}:
                    continue
                if set(left).issubset({"-", ":"}) or set(right).issubset({"-", ":"}):
                    continue

                raw_priority = right.lower()
                if raw_priority.startswith("high"):
                    clean_priority = "High"
                elif raw_priority.startswith("medium"):
                    clean_priority = "Medium"
                elif raw_priority.startswith("low"):
                    clean_priority = "Low"
                else:
                    continue

                parsed_ai_actions.append({"Action Item": left, "Priority": clean_priority})

            editable_ai_actions_df = pd.DataFrame(columns=["Action Item", "Priority"])
            if parsed_ai_actions:
                ai_actions_df = pd.DataFrame(parsed_ai_actions)
                editable_ai_actions_df = st.data_editor(
                    ai_actions_df,
                    use_container_width=True,
                    num_rows="dynamic",
                    key="ai_actions_editor",
                    column_config={
                        "Priority": st.column_config.SelectboxColumn(
                            "Priority",
                            options=["High", "Medium", "Low"],
                            required=True,
                        )
                    },
                )
            else:
                st.warning("AI response could not be parsed into table format. Showing raw output below.")
                st.text(ai_action_text)

            if st.button("Save AI Actions", key="save_ai_actions_button"):
                saved_count = 0
                existing_actions = set(action_df["Action"].astype(str).str.strip().str.lower()) if not action_df.empty else set()

                rows_to_save = editable_ai_actions_df.to_dict("records")

                for row in rows_to_save:
                    action_text = str(row.get("Action Item", "")).strip()
                    clean_priority = str(row.get("Priority", "")).strip().title()

                    if not action_text or clean_priority not in {"High", "Medium", "Low"}:
                        continue

                    if action_text.lower() in existing_actions:
                        continue

                    action_sheet.append_row([action_text, clean_priority, AI_ACTION_SOURCE])
                    existing_actions.add(action_text.lower())
                    saved_count += 1

                if saved_count > 0:
                    clear_google_sheet_read_cache()
                    mark_sync_event("Saved AI actions")
                    st.session_state["ai_actions_text"] = ""
                    set_flash_message("action", "success", f"Saved {saved_count} AI actions successfully!")
                    st.rerun()
                else:
                    st.warning("No valid AI actions found to save.")

        st.write("### ✏️ Edit Action")
        if not action_df.empty and all(col in action_df.columns for col in ACTION_SHEET_COLUMNS):
            action_options = ["Select an action"] + [
                f"{row_num}: {getattr(row, 'Action', '')} ({getattr(row, 'Priority', '')} | {getattr(row, 'Source', '')})"
                for row_num, row in enumerate(action_df.itertuples(index=False), start=2)
            ]
            selected_action_label = st.selectbox(
                "Select Action",
                action_options,
                key="action_select_to_edit",
            )

            if selected_action_label != "Select an action":
                selected_index = action_options.index(selected_action_label) - 1
                selected_sheet_row = int(selected_action_label.split(":", 1)[0])
                selected_row = action_df.iloc[selected_index]

                if st.session_state.get("edit_action_source_row") != selected_action_label:
                    st.session_state["edit_action_text"] = str(selected_row["Action"])
                    st.session_state["edit_action_priority"] = str(selected_row["Priority"]).strip().title()
                    st.session_state["edit_action_source"] = str(selected_row["Source"]).strip()
                    st.session_state["edit_action_source_row"] = selected_action_label

                new_action = st.text_input("Action", key="edit_action_text")
                source_options = [TEAM_ACTION_SOURCE, AI_ACTION_SOURCE]
                current_source = str(st.session_state.get("edit_action_source", TEAM_ACTION_SOURCE)).strip()
                if current_source not in source_options:
                    current_source = TEAM_ACTION_SOURCE
                    st.session_state["edit_action_source"] = TEAM_ACTION_SOURCE

                priority_options = ["High", "Medium", "Low"]
                current_priority = str(st.session_state.get("edit_action_priority", "Medium")).strip().title()
                if current_priority not in priority_options:
                    current_priority = "Medium"
                    st.session_state["edit_action_priority"] = "Medium"

                new_priority = st.selectbox(
                    "Priority Status",
                    priority_options,
                    index=priority_options.index(current_priority),
                    key="edit_action_priority",
                )
                new_source = st.selectbox(
                    "Action Source",
                    source_options,
                    index=source_options.index(current_source),
                    key="edit_action_source",
                )

                if st.button("Update Action", key="update_action_button"):
                    if new_action.strip():
                        action_sheet.update_acell(f"A{selected_sheet_row}", new_action.strip())
                        action_sheet.update_acell(f"B{selected_sheet_row}", new_priority)
                        action_sheet.update_acell(f"C{selected_sheet_row}", new_source)
                        clear_google_sheet_read_cache()
                        mark_sync_event("Updated action item")
                        st.session_state["action_select_to_edit"] = "Select an action"
                        clear_session_keys("edit_action_text")
                        st.session_state["edit_action_priority"] = "Medium"
                        st.session_state["edit_action_source"] = TEAM_ACTION_SOURCE
                        st.session_state.pop("edit_action_source_row", None)
                        set_flash_message("action", "success", "Action updated successfully!")
                        st.rerun()
                    else:
                        st.warning("Action cannot be empty.")
    except Exception as error:
        st.error(f"Unable to load Action Tracker: {error}")

with tab7:
    show_flash_message("fishbone")
    st.subheader("🐟 Fishbone Root Cause Analysis")

    # -------------------------
    # Problem Statement
    # -------------------------
    problem = st.text_input(
        "🎯 Problem Statement",
        value=st.session_state.get("ai_problem", "High Defects / Spillover"),
        key="fishbone_problem_input",
    )

    # -------------------------
    # Categories
    # -------------------------
    categories = ["People", "Process", "Tools", "Requirements", "Dependencies"]

    if "fishbone_data" not in st.session_state:
        st.session_state.fishbone_data = {cat: [] for cat in categories}

    # Keep categories aligned when list changes.
    for cat in categories:
        if cat not in st.session_state.fishbone_data:
            st.session_state.fishbone_data[cat] = []

    # -------------------------
    # Add Causes (Interactive)
    # -------------------------
    st.write("### ➕ Add Causes")

    utility_col1, utility_col2 = st.columns([1, 1])
    if utility_col1.button("🧹 Clear All Causes", key="fishbone_clear_all"):
        st.session_state.fishbone_data = {cat: [] for cat in categories}
        st.rerun()

    total_cause_count = sum(len(st.session_state.fishbone_data.get(cat, [])) for cat in categories)
    utility_col2.metric("Total Causes", total_cause_count)

    cols = st.columns(len(categories))

    for i, cat in enumerate(categories):
        with cols[i]:
            st.markdown(f"**{cat}**")

            new_cause = st.text_input(f"Add cause in {cat}", key=f"input_{cat}")

            add_col, clear_col = st.columns([1, 1])
            if add_col.button("+ Add", key=f"btn_{cat}"):
                if new_cause.strip():
                    st.session_state.fishbone_data[cat].append(new_cause.strip())
                    clear_session_keys(f"input_{cat}")
                    st.rerun()

            if clear_col.button("Clear", key=f"clear_{cat}"):
                st.session_state.fishbone_data[cat] = []
                st.rerun()

            for cause_index, cause in enumerate(list(st.session_state.fishbone_data[cat])):
                cause_text_col, cause_delete_col = st.columns([5, 1])
                cause_text_col.caption(f"{cause_index + 1}. {cause}")
                if cause_delete_col.button("✕", key=f"del_{cat}_{cause_index}"):
                    st.session_state.fishbone_data[cat].pop(cause_index)
                    st.rerun()

    # -------------------------
    # AI Suggestions
    # -------------------------
    st.write("### 🤖 AI Suggested Causes")

    if st.button("💡 Generate AI Suggestions", key="fishbone_generate_ai_suggestions"):
        api_key, key_source, secret_keys = get_openai_api_key()

        if not api_key:
            st.error("OpenAI key is missing. Add OPENAI_API_KEY in Streamlit secrets and restart the app.")
            st.caption(
                f"Diagnostics: key_source={key_source}; top_level_secrets={', '.join(secret_keys) if secret_keys else 'none'}"
            )
        else:
            prompt = f"""
Problem: {problem}

Suggest root causes under:
People, Process, Tools, Requirements, Dependencies

Format:
Category: cause1, cause2
"""

            try:
                client = OpenAI(api_key=api_key)
                response = client.chat.completions.create(
                    model="gpt-4.1-mini",
                    messages=[{"role": "user", "content": prompt}],
                    temperature=0.3,
                )
                output = response.choices[0].message.content or "No suggestions generated."
                st.text(output)
            except Exception as ai_error:
                st.error(f"Unable to generate AI suggestions: {ai_error}")

    # -------------------------
    # Graphviz Fishbone Diagram
    # -------------------------
    st.write("### 🐟 Fishbone Diagram")

    def _dot_escape(value: str) -> str:
        return str(value).replace("\\", "\\\\").replace('"', '\\"')

    def _dot_multiline(value: str, width: int = 24) -> str:
        wrapped_value = textwrap.fill(str(value), width=width)
        return _dot_escape(wrapped_value).replace("\n", "\\n")

    diagram_density = st.select_slider(
        "Diagram Spacing",
        options=["Compact", "Balanced", "Comfortable"],
        value="Comfortable",
        key="fishbone_diagram_density",
    )

    spacing_map = {
        "Compact": (0.5, 0.8),
        "Balanced": (0.8, 1.1),
        "Comfortable": (1.1, 1.5),
    }
    nodesep, ranksep = spacing_map.get(diagram_density, (1.1, 1.5))

    problem_safe = _dot_multiline(problem, width=28)
    dot_lines = [
        "digraph Fishbone {",
        "rankdir=LR;",
        f"graph [nodesep={nodesep}, ranksep={ranksep}, splines=true, pad=0.3];",
        "node [fontname=Helvetica, fontsize=12, margin=0.15];",
        "edge [penwidth=1.2, color=gray35];",
        f'Problem [label="{problem_safe}", shape=box, style="filled,rounded", fillcolor="#fca5a5", color="#b91c1c", penwidth=1.6];',
    ]

    for i, (cat, causes) in enumerate(st.session_state.fishbone_data.items()):
        cat_node = f"cat_{i}"
        cat_safe = _dot_multiline(cat, width=16)
        dot_lines.append(
            f'{cat_node} [label="{cat_safe}", shape=ellipse, style=filled, fillcolor="#bfdbfe", color="#1d4ed8", penwidth=1.4];'
        )
        dot_lines.append(f"{cat_node} -> Problem;")

        for j, cause in enumerate(causes):
            cause_node = f"{cat_node}_{j}"
            cause_safe = _dot_multiline(cause, width=22)
            dot_lines.append(
                f'{cause_node} [label="{cause_safe}", shape=box, style="rounded,filled", fillcolor="#f8fafc", color="#94a3b8"];'
            )
            dot_lines.append(f"{cause_node} -> {cat_node};")

    dot_lines.append("}")
    st.graphviz_chart("\n".join(dot_lines))

    # -------------------------
    # Identify Root Cause (Simple logic)
    # -------------------------
    st.write("### 🔍 Identify Root Cause")

    if st.button("Find Root Cause", key="fishbone_find_root_cause"):
        if any(len(st.session_state.fishbone_data[cat]) > 0 for cat in categories):
            max_cat = max(
                st.session_state.fishbone_data,
                key=lambda k: len(st.session_state.fishbone_data[k]),
            )
            st.success(f"Primary Problem Area: {max_cat}")
        else:
            st.info("Add at least one cause to identify the primary problem area.")

    # -------------------------
    # Generate Actions
    # -------------------------
    st.write("### 🚀 Suggested Actions")

    if st.button("Generate Actions from Fishbone", key="fishbone_generate_actions"):
        all_causes = []
        for cat, causes in st.session_state.fishbone_data.items():
            for cause in causes:
                all_causes.append(f"{cat}: {cause}")

        if not all_causes:
            st.info("Add causes before generating actions.")
        else:
            api_key, key_source, secret_keys = get_openai_api_key()

            if not api_key:
                st.error("OpenAI key is missing. Add OPENAI_API_KEY in Streamlit secrets and restart the app.")
                st.caption(
                    f"Diagnostics: key_source={key_source}; top_level_secrets={', '.join(secret_keys) if secret_keys else 'none'}"
                )
            else:
                prompt = f"""
Problem: {problem}

Causes:
{chr(10).join(all_causes)}

Suggest 3-5 actionable improvements.
"""

                try:
                    client = OpenAI(api_key=api_key)
                    response = client.chat.completions.create(
                        model="gpt-4.1-mini",
                        messages=[{"role": "user", "content": prompt}],
                        temperature=0.3,
                    )
                    st.write(response.choices[0].message.content or "No actions generated.")
                except Exception as ai_error:
                    st.error(f"Unable to generate fishbone actions: {ai_error}")

